### ISSUE TITLE
TickTick reporting too many requests

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#164]
I am getting this today in Obsidian:

![image](https://github.com/user-attachments/assets/43ba5a95-eaca-48cc-b236-5b7dc51e820c)

**Comment by Dennyyusuf** [comment]
same to me as well today

**Comment by IMXeno123** [comment]
same

**Comment by gyuraam** [comment]
same....

**Comment by jee-ee** [comment]
It looks like the issue is now with the _version_ property in `x-device`. 

As a temporary workaround, you can go into the folder of your vault and modify the file `.obsidian/plugins/tickticksync/main.js` and search for `"version":4576`

Replace the id `"version":4576` with any other 4 digit number (e.g `"version":5192` and save the file. Reload Obsidian and things should work now.

For the proper fix, you will need to wait for the maintainer 😃

**Comment by thesamim** [comment]
As always: Thanks @jee-ee 

Tracking through: https://github.com/thesamim/TickTickSync/issues/165
