### ISSUE TITLE
Project Assignment Not Syncing Between Laptops in Obsidian and Ticktick

### ISSUE THREAD

**Issue by Dennyyusuf** [thesamim/TickTickSync#172]
**Describe the bug**
I’m using two laptops with Obsidian and Ticktick Sync installed on both, and I frequently switch between them. However, once a default project has been assigned to a note in Obsidian on one laptop, the configuration does not sync to the other laptop. As a result, all configured tasks for that project are shifted to the Inbox when I switch laptops.

**Set up questions:
- Is this your first time using TickTickSycn? No
- Is your Vault shared across devices? Yes
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)?  Obsidian Sync
- Do you have a Default Folder Location? Yes
- Do you have a Default project? Yes
- Do you have "Full Vault Sync" enabled? Yes
- Do you have "Debug Mode" enabled? Yes
- Do you have either of the "Limit Synchronization" settings set? Yes set to 25 sec

**Comment by thesamim** [comment]
@Dennyyusuf : Any update on this?

**Comment by Dennyyusuf** [comment]
Hello, thanks for checking on me.

I am still having problems syncing the project, although all sync options
are checked, including the plugins.

**Comment by thesamim** [comment]
The project to file relationship is maintained in `<vault>\.obsidian\plugins\TickTickSync\data.json`

If that file is not getting synchronized for some reason, that's going to cause issues. 

Suggestion:
Next time you have both laptops together, and are convinced that a Sync has happened, compare the file size and dates of `<vault>\.obsidian\plugins\TickTickSync\data.json` on the two laptops. They should be the same. 

I would also check if your other plugins' data files are being synced. 

If they are not, I would check into things like folder permissions and Sync configurations to make sure that `.obsidian` and below are indeed getting synced.

BTW: I made an assumption: Both laptops are running the same operating system right? Because different OS' treat dotted folder (`.obsidian`) differently, I believe.

**Comment by thesamim** [comment]
@Dennyyusuf : assuming that since I haven't heard from you in a while that this has sorted itself out. If it hasn't please re-open with more details.
