### ISSUE TITLE
Do not add the link to file in the name of the task

### ISSUE THREAD

**Issue by martin-arg** [thesamim/TickTickSync#55]
Hi I'm testing the plugin to discover that all my tasks have the name change to add the link to the obsidian note, can this be disabled? Or move to the task note?

**Comment by rbtmarshall** [comment]
I don't understand the usefulness of this backlink on the initial synch of all the tasks from TickTick to Obsidian. 

Where I do not see its usefulness:
- On the initial sync, TickTickSync downloads all tasks from TickTick, and puts them into a separate Obsidian page for each TickTick list we have our tasks in. The root folder is customized in the extension settings.
- the backlink redirects to that task location on the aggregate page in Obsidian for the List Name.
- for this initial sync, it appears to serve no purpose from what I can see in my short time of use. Because a backlink to a page full of task names and another link to TickTick web for that task


Wher I can see some usefulness:
Creating a new task via Obsidian Task, on another Obsidian page, daily journal, or whatever.  If that task is taggeg with #ticktick, it creates a task in the TickTick webpage, and that backlink from the task in TickTick now points to a page in Obsidian with potential use.

I'm pretty new to Obsidian and Tick Tick, but those are my initial thoughts with this plugin as it relates to the Issue.

**Comment by martin-arg** [comment]
For me if there is not need for the plugin for the link, it should be optional. in my case it fills me with clutter the name of the task, also, as far as I can see, it copies the due date in the name.
It would be nice if this could be optional.

**Comment by thesamim** [comment]
That was a feature that was specifically requested. Please start a poll in the discussion section. If there are enough folks who want that removed I will do so.
