### ISSUE TITLE
My whole Ticktick got messed up on first sync

### ISSUE THREAD

**Issue by zekeadam** [thesamim/TickTickSync#58]
Old completed tasks marked as uncomplete, task names messed up, dates removed, tasks duplicated, my whole ticktick is a mess now. Is there any way to reverse everything the plugin did without going trough everything manually which would take a day? 

Edit: Found the backup file, Had to delete and restore everything which got back most of the stuff but all of the time trackings are now unlinked from my projects which sucks.

**Comment by thesamim** [comment]
Sorry you went through that.

Please updated to 1.0.16. Please turn on debug mode in settings. If this happens again, please send me your console log.

**Comment by akseron** [comment]
Hi! The same happened to me as the author wrote, so I tried debugging a bit to see what could have caused it. After trying multiple methods: reopening Obsidian after installation of Tasks and TickTickSync, clean installation of TickTickSync, trying multiple times, I think I found the reason behind the problem. The presence of emoji's in TickTick folder names (which I had), seemed to at the very least cause every task in that folder with a due date without a specified time, to be moved one day earlier. Every test run I ran caused syncing to move all my tasks (with a due date without a specified time)  to one day earlier, except the one where I removed all emoji's from folder names. At the time of the writing of this comment I have added an emoji to only one folder and synced my tasks, this indeed caused only the tasks with an unspecified time in that folder to be moved one day.

**Comment by akseron** [comment]
I have the same error, which I suspect is due to timezones and the Tasks note you made about queries vs due dates.
My console log contains some sensitive information, but these are tidbits which may help:

> plugin:tickticksync:59291 No Token
> TickTickRestAPI @ plugin:tickticksync:59291
> plugin:tickticksync:59306 Uncaught (in promise) Error: API Not Initialized. Please restart Obsidian.
>     at TickTickRestAPI.initializeAPI (plugin:tickticksync:59306:13)
>     at TickTickSync.initializePlugin (plugin:tickticksync:68975:32)
>     at TickTickSync.onload (plugin:tickticksync:68777:16)

> plugin:tickticksync:66932 File path not found for 65cbe3288f08e37445a18e7b, returning D83CDF8AVerjaardagen.md instead. 
> getFilepathForProjectId @ plugin:tickticksync:66932
> plugin:tickticksync:67472 Creating new file: TickTick/D83CDF8AVerjaardagen.md
> addTasksToFile @ plugin:tickticksync:67472
> plugin:tickticksync:67547 Could not add Tasks to file TickTick/D83CDF8AVerjaardagen.md 
>  Error: TypeError: Cannot read properties of undefined (reading 'set')

> plugin:tickticksync:68642 An error occurred while synchronizing: TypeError: Cannot read properties of null (reading 'path')
>     at FileOperation.addProjectTasksToFile (plugin:tickticksync:67547:57)
>     at async FileOperation.addTasksToFile (plugin:tickticksync:67496:20)
>     at async SyncMan.syncTickTickToObsidian (plugin:tickticksync:68573:22)
>     at async TickTickSync.scheduledSynchronization (plugin:tickticksync:69131:24)
>     at async eval (plugin:tickticksync:59069:11)

> The timestamps are NaN minutes apart.
> Title modified for task 65cbe3288f08e37445a18ee8
> "New:" Verjaardag [TickTick/D83CDF8AVerjaardagen.md](obsidian://open?vault=Obsidian&file=TickTick/D83CDF8AVerjaardagen.md)
> "Cached:" Verjaardag [TickTick/D83CDF8AVerjaardagen.md](obsidian://open?vault=Obsidian&file=TickTick/D83CDF8AVerjaardagen.md)
> Due date modified for task 65cbe3288f08e37445a18ee8
> 2024-03-24T08:00:00.000+-100 old:  2024-03-24T23:00:58.000+0000
> Task Changed:  65cbe3288f08e37445a18ee8 
> Task 65cbe3288f08e37445a18ee8 is updated.
> Content was changed.
> Due date was changed.

My timezone is Amsterdam (GMT+1) .

**Comment by thesamim** [comment]
@akseron : I've tried reproducing this, but am not able to. 

I have: 😁 This folder/💼 Start in emoji folder.md (I've tried with just emoji in folder, just emoji in file name, and emoji in both) And the due dates do not shift. Is it possible you have some non-latin letters in your folder names?

Did find one bug though: updating a due date from Obsidian seems to mess up due date on TickTick. But I don't think that's what you're experiencing. If I'm understanding correctly: you are only dealing with due dates/times set on TickTick. Is that correct?

Opened [Issue 62](https://github.com/thesamim/TickTickSync/issues/62) to track.

> > plugin:tickticksync:68642 An error occurred while synchronizing: TypeError: Cannot read properties of null (reading 'path')

Right before this line, you should have seen: `Creating new file: ${folder.path}/${taskFile}` where folder.path is the folder the file would have been created in, and taskFile would have been the file. Could you please let me know if you did, and if you saw anything strange in the way the folder name/file name were displayed?

> > The timestamps are NaN minutes apart.

This worries me. There should not be a situation where the due date difference results in an invalid number. Opened [Issue 63](https://github.com/thesamim/TickTickSync/issues/63) to track.

> > Title modified for task 65cbe3288f08e37445a18ee8
> > "New:" Verjaardag TickTick/D83CDF8AVerjaardagen.md
> > "Cached:" Verjaardag TickTick/D83CDF8AVerjaardagen.md

Q: did you use non-latin characters in the Title? Those two titles look to be the same. However, they did not compare the same....

> > Due date modified for task 65cbe3288f08e37445a18ee8
> > 2024-03-24T08:00:00.000+-100 old:  2024-03-24T23:00:58.000+0000

In this example, the dates match (March 24th) but there's a 14 hour time difference.

Did you have a specific time in the due date on Ticktick? Was it the AM time or the PM time?

> 
> What I found interesting was that the start/due date were detected as February 20th, while it was in fact noted for February 21st on TickTick. My timezone is Amsterdam (GMT+1). I have altered the names of the actual file for privacy reasons.

Could you have been testing close to midnight?

Favor please:
Take a back up from TickTickSync settings ("Backup TickTick data"). Take a look at the resulting CSV file.

Take a look at the Due Date, Timezone, Is All Day columns. Do they match your expectations?

**Comment by thesamim** [comment]
Thank you so much for doing all this research. I will got through it in detail  shortly. 

But first:
> Maybe a timezone issue which causes it to work for some and for some not?
I am now convinced it is a timezone issue. Question: is your Obsidian timezone the same as the TickTick timezone?

**Comment by akseron** [comment]
Hi Samim thank you for your response,

I am not sure, I could not find a timezone setting for Obsidian, but looking around I figured it would probably be the same as my system, in which case yes it should be.

**Comment by akseron** [comment]
Tickticksync error message when creating tasks while only the inherent Ticktick inbox exists.
![image](https://github.com/thesamim/TickTickSync/assets/71043418/f65040b5-b425-41db-bc75-22f682199d7c)

**Comment by thesamim** [comment]
@akseron :  I'm not sure I've taken care of all the issues. I can only do limited testing with timezones...

Favor please. The attached version of the plugin has way more logging to help me understand what's going on.

Could you please: 

1. Change your settings so that you are only synchronization one project (so that if it's not right, we're limiting the damage to one project.)
2. Make a copy of your current `main.js` file in `<vault directory>\.obsidian\plugins\tickticksync`
3. extract the files in the attached zip file to that directory
4. make sure that debug mode is on
5. test again
6. in the icon bar, you will see a new icon ![image](https://github.com/thesamim/TickTickSync/assets/5315625/01c1c94f-4cfa-48be-8e3b-fec65c0474df). When you click it, you will see a popup notice with your time zone. 

Please let me know what happens with the testing, and what your time zone is set to in the popup notice.

Thanks in advance.


[tickticksync.zip](https://github.com/thesamim/TickTickSync/files/14321262/tickticksync.zip)

**Comment by akseron** [comment]
Hi samim, I could not find the icon in my icon bar, however this setting might be your answer:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/bd765a67-ce70-4d84-b353-349e43012f0b)

The two times both have the same timezone now, however their timestamps are 1 day apart, meaning all my dates are placed one day earlier. There is some improvement however, as they do retain the correct time at 0:00 instead of being put to 13/14:00. 

These are error messages which occurred:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/886c4687-cb0e-4d33-b9b8-4a69e88a8cf6)

**Comment by thesamim** [comment]
@akseron 
One more time please. There was a bug with converting UTC to Local time. I hope I fixed it.

I could not reproduce:
> These are error messages which occurred: ![image](https://private-user-images.githubusercontent.com/71043418/305722618-886c4687-cb0e-4d33-b9b8-4a69e88a8cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzQ0NjgsIm5iZiI6MTcwODM3NDE2OCwicGF0aCI6Ii83MTA0MzQxOC8zMDU3MjI2MTgtODg2YzQ2ODctY2IwZS00ZDMzLWI5YjgtNGE2OWU4OGE4Y2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIwMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MzE4ZWY5MjE0OGU1MTRlYTU1YWVmOGQ1MzFlZmU5MjA4YTQ4YjQwYjhjNzA3NjdjMzBhYjVkZWQzNTQ2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPfj9NuXrubsRiMoBcV8HIMtLdRmk1OkoqVmHzY6x7g)
> 

If you can reproduce it: Please let me know the exact sequence of events that go to that error. 



Could not reproduce the following either. All those errors indicate that  the TickTick servers were having issues at the time.

> Error messages on a second run where I changed a setting in main.js from America/New_York to Europe/Amsterdam (probably did nothing): ![image](https://private-user-images.githubusercontent.com/71043418/305723946-fe8c5435-8ca0-4450-bd98-95728ee8a29c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzQ0NjgsIm5iZiI6MTcwODM3NDE2OCwicGF0aCI6Ii83MTA0MzQxOC8zMDU3MjM5NDYtZmU4YzU0MzUtOGNhMC00NDUwLWJkOTgtOTU3MjhlZThhMjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIwMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNmFkMmZiMjU4MThjYmRhYWM4NGRkY2YzYTgzNGY1YzRkYWJkMDEwMTgyODI5MmI1NWYxNzEyMzFjODUxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XONsMAsqdmCG0FyfkphMbtTsaUMKu7hma8s6ouA4Eyk)
> 

Again: if you can give me reproduction steps, I would be glad to fix (or mitigate if I cannot fix.)

> Edit: the icon appeared ![image](https://private-user-images.githubusercontent.com/71043418/305724836-56bd8679-badb-4e22-983a-da2406b3cbfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzQ0NjgsIm5iZiI6MTcwODM3NDE2OCwicGF0aCI6Ii83MTA0MzQxOC8zMDU3MjQ4MzYtNTZiZDg2NzktYmFkYi00ZTIyLTk4M2EtZGEyNDA2YjNjYmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIwMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MzBkYWIwODQ3Zjc0ZDc4M2E0MjU5YWI0MTA4ZGE0NDBhNDU5NTc2NGNkNTBjMWRmNWFmODVlYmY1ODNmOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEPrVsh-goAKlObb_GkSa_dmyvSq6_xtY1fOWxaKlu0)
> 

Good! No surprise there. 


> Somehow the synced list ended up disappearing after pressing login again and prompted this window: ![image](https://private-user-images.githubusercontent.com/71043418/305725488-0599ff68-8b0b-41bf-870b-2ebcf4afbed6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzQ0NjgsIm5iZiI6MTcwODM3NDE2OCwicGF0aCI6Ii83MTA0MzQxOC8zMDU3MjU0ODgtMDU5OWZmNjgtOGIwYi00MWJmLTg3MGItMmViY2Y0YWZiZWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIwMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Y2YwMWRkOWE1MzVjMDM3Y2RhNjBjMGFjYWNmNmEyZDY2YzIyM2ZkMmFkNjRkOGFjNmU0MDAyMDE1MTczODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8C3U0qdYw8XH6dFWxW0SCRWeklp12loqXY2abFOalJU)

There is no code in TickTickSync that would trigger that screen. Which leads me to a question I should have asked from the beginning: What other plugins are you running?

Regardless: Please try again with the attached.
[tickticksync.zip](https://github.com/thesamim/TickTickSync/files/14336690/tickticksync.zip)

**Comment by akseron** [comment]
> I could not reproduce:
> 
>     These are error messages which occurred: image
> 
> If you can reproduce it: Please let me know the exact sequence of events that go to that error.

These errors usually occur after I reinstall Tickticksync. I usually attempted to entirely delete both Tasks and Tickticksync every time to ensure that any old tasks were removed from the system. After some experimenting I was contemplating that this caused Tickticksync to not be properly setup, which would also explain the fact that the icon was not appearing at first. However, even after Tickticksync was setup as it should be (as far as how a layman would set it up), the syncing still went wrong at some point (If this happens again I'll document an example).

> Could not reproduce the following either. All those errors indicate that the TickTick servers were having issues at the time.

I am guessing that Tickticksync really needs a reboot or two before being setup entirely considering this is what I usually needed during experimenting for the icon of before to appear (I will mention whether this is still the case in a bit).

> There is no code in TickTickSync that would trigger that screen. Which leads me to a question I should have asked from the beginning: What other plugins are you running?

I am using the following list of plugins:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/7d7950b3-c259-4fba-ab59-225351589c31)

At an earlier stage of experimenting, I did try turning off all plugins and I believe (not too sure however) that the bug still happened. It sometimes occurred when I tried pressing Login / setting a folder by using the + button. I will be turning trying your solution with all plugins turned on, and in case it does not work I will try again with all plugins turned off.

> Regardless: Please try again with the attached.
> [tickticksync.zip](https://github.com/thesamim/TickTickSync/files/14336690/tickticksync.zip)

Will do!

**Comment by akseron** [comment]
1. Installed TickTickSync and did not touch any setting yet.
2. Closed Obsidian and changed the plugin files with yours.
(Getting a prompt 'Please login from Settings.', cannot see your icon yet)
3. Pressed login once, already logged in in the pop-up screen, however TickTickSync still displays login setting.
4. Pressed login again, Tickticksync has not detected a login (repeat this about 10 times)
5. Trying to log out from the already logged in pop-up.
6. Pressing login after logging in from the pop-up works now and Tickticksync is loaded succesfully.
7. Set `Default folder location` to `Ticktick/Tasks`
8. Set `Project` to `Verjaardagen`, receive a notification `Did not find a default Project File for Project Verjaardagen. Please create a file and set it's default to this project, or select a file to be the default for this project.
`9. Set `Default project` to `Verjaardagen`
10. Turn on `Debug mode` 
11. `Check database`
12. At this point I notice that your icon still has not appeared, so I will restart Obsidian.
13. Upon restarting Obsidian, the icon is loaded, an icon called TickTickSync is also loaded.
14. Sync using `TickTickSync`.

Beginning of the developer console:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/5f26dfc0-bd7c-4ed8-a300-b661a3ba8cae)

Ending of the developer console:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/bdba5c48-d5af-4a64-b9fb-61e3a7df5fd4)

**Comment by thesamim** [comment]
So... Those dates now look correct to me. Are they not what you're expecting?

**Comment by akseron** [comment]
1. Windows 11
2. I have it synced up through Syncthing
3. I have my phone (Android) connected through Syncthing

**Comment by thesamim** [comment]
@akseron : That's pretty much my setup, except I have my vault on a onedrive folder. I have not encountered those issues. Please check your syncthing log to see if there are any conflicts there.

About the dates: are they matching up with what's on TickTick now?

**Comment by akseron** [comment]
> @akseron : That's pretty much my setup, except I have my vault on a onedrive folder. I have not encountered those issues. Please check your syncthing log to see if there are any conflicts there.
> 

I will try to do so when I have some spare time.

> About the dates: are they matching up with what's on TickTick now?

Yes and no, the dates end up being synced correctly, however the times associated with the dates are incorrect.

**Comment by thesamim** [comment]
@akseron 
> Yes and no, the dates end up being synced correctly, however the times associated with the dates are incorrect.

One more time please. I think I found the time issue. But I'm still not sure why updating the main.js is causing so many issues.

[tickticksync.zip](https://github.com/thesamim/TickTickSync/files/14350210/tickticksync.zip)

**Comment by akseron** [comment]
> But I'm still not sure why updating the main.js is causing so many issues.

I figured out how the error occurred with regards to login. I used the following way to recreate the error: use Tickticksync properly without any sync yet, login and create a folder to save your files by clicking on the + button. Afterwards restart Obsidian, and before Tickticksync is done synchronizing, delete the folder you previously created. After Tickticksync synchronizes you repeat the steps to create the same folder by clicking on + and afterwards press login and voila, the error occurs. This is not dependent off any other plugins, however plugins are triggered when the error happens. The reason why I had it occur to me, is that oftentimes Tickticksync took a longer time for me to sync somehow, however in a regular case the chance of someone deleting the file in this short interval before Tickticksync is done synchronizing, is fairly low I believe.

`Untitled `and `Untitled ` canvas are created in case you delete the Tasks file here, before Tickticksync is done synchronizing:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/dae7d5f5-75df-4648-9c14-67c1dc5f8939)

These were the settings in Tickticksync:
![image](https://github.com/thesamim/TickTickSync/assets/71043418/949b121a-a728-43c7-bdb4-132f162d61a4)

So that should clear things up a bit.

**Comment by thesamim** [comment]
Cool. Thanks. Will keep an eye on that.

Now: How are the dates and times looking on the tasks?

**Comment by akseron** [comment]
Okay took me a bit to get everything running, but I changed my private values inside the files so that I could share some direct data copies with you.

I ran the sync 5 times, without touching anything in the Obsidian or Ticktick dates. I kept seeing something change, so I kept running it until I realised one date kept having a day added on top, thus stopping my runs as I figured it was not necessary to continue.

The problem remains that dates are set correctly, however the time is set at 12:00 instead of 00:00. Also the last task in the list seems to keep getting a date added everytime a sync is completed.

Here are the dates and csv data before:
![Pasted image 20240221013008](https://github.com/thesamim/TickTickSync/assets/71043418/7458c707-3bfe-418e-bb43-b3cc597556ab)
[TickTick-backup-2024-02-21-special-test-before.csv](https://github.com/thesamim/TickTickSync/files/14352577/TickTick-backup-2024-02-21-special-test-before.csv)

Here are the dates and csv data after:
![Pasted image 20240221013428](https://github.com/thesamim/TickTickSync/assets/71043418/6ec24807-f3fe-4ed0-adfe-4b4d0c646d91)
[TickTick-backup-2024-02-21-special-test-after.csv](https://github.com/thesamim/TickTickSync/files/14352578/TickTick-backup-2024-02-21-special-test-after.csv)

Here is the log:
[obsidian.md-1708476197899.log](https://github.com/thesamim/TickTickSync/files/14352586/obsidian.md-1708476197899.log)

**Comment by akseron** [comment]
Checked for another file which only has durations inside of it, all the correct dates were picked, however the durations in Ticktick and Obsidian were both changed to only the start time, with no end time.

**Comment by thesamim** [comment]
@akseron : please try 1.0.17 update
Thanks for All your help. 
Also please check out the Read me file acknowledgment section. 😁
